update run to work with cpp

diff --git a/run b/run
--- a/run
+++ b/run
@@ -13,7 +13,7 @@ if [ -f "$ConfigFile" ]; then
 fi
 
 ProblemGiven="false"
-SetProblem () {
+SetProblem() {
   if [ "$ProblemGiven" = "true" ]; then
     echo "ERROR: Problem given multiple times, but it must be given at most once."
     exit 1
@@ -24,7 +24,7 @@ SetProblem () {
 }
 
 CaseIdGiven="false"
-SetCaseId () {
+SetCaseId() {
   if [ "$CaseIdGiven" = "true" ]; then
     echo "ERROR: Problem given multiple times, but it must be given at most once."
     exit 1
@@ -35,7 +35,7 @@ SetCaseId () {
 }
 
 LanguageGiven="false"
-SetLanguage () {
+SetLanguage() {
   if [ "$LanguageGiven" = "true" ]; then
     echo "ERROR: Language given multiple times, but it must be given at most once."
     exit 1
@@ -117,33 +117,51 @@ echo "Lang=$Lang" > "$ConfigFile"
 echo "Problem=$Problem" >> "$ConfigFile"
 echo "CaseId=0" >> "$ConfigFile"
 
-SOLUTION_FILE="workspace/$Problem/main.$Lang"
+SolutionFile="workspace/$Problem/main.$Lang"
 
 if [ "$Lang" = "cpp" ]; then
-  echo "Compiling cpp file: $SOLUTION_FILE"
+  if cmp --silent -- "$SolutionFile" "build/last_compiled.txt"; then
+    echo "No changes on $SolutionFile. Re using compiled binary..."
+    SolutionFile="build/solution"
+  else
+    echo "Compiling cpp file: $SolutionFile"
+    gcc "$SolutionFile" -o "build/solution" -std=c++20 -Wall -Wextra -O2 -Wshadow -pedantic -Wformat=2 -Wfloat-equal -Wconversion -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC  -fsanitize=address -fno-sanitize-recover -fstack-protector
+    cp "$SolutionFile" "build/last_compiled.txt"
+    SolutionFile="build/solution"
+  fi
+fi
+
+if ! test -f "$SolutionFile"; then
+  echo "Solution file not found: $SolutionFile"
   exit 0
 fi
 
-if ! test -f "$SOLUTION_FILE"; then
-  echo "Solution file not found: $SOLUTION_FILE"
-  exit 0
-fi
+RunSolution() {
+  if [ "$Lang" = "go" ]; then
+    go run "$SolutionFile"
+  else
+    ./$SolutionFile
+  fi
+}
 
 RunTestCase() {
-  INPUT_FILE="workspace/$Problem/cases/$CaseId.in"
-  OUTPUT_FILE="workspace/$Problem/cases/$CaseId.txt"
-  EXPECTED_FILE="workspace/$Problem/cases/$CaseId.out"
+  InputFile="workspace/$Problem/cases/$CaseId.in"
+  OutputFile="workspace/$Problem/cases/$CaseId.txt"
+  ExpectedOutputFile="workspace/$Problem/cases/$CaseId.out"
 
-  if ! test -f "$INPUT_FILE"; then
-    echo "Input file not found: ${INPUT_FILE}"
+  if [ ! -f "$InputFile" ]; then
+    echo "Input file not found: ${InputFile}"
     exit 1
   fi
 
-  # TODO: check if exit status code is not 0 and show error
-  go run "$SOLUTION_FILE" <"$INPUT_FILE"> "$OUTPUT_FILE"
+  if [ -f "$OutputFile" ]; then
+    rm "$OutputFile"
+  fi
 
-  if test -f "$EXPECTED_FILE"; then
-    if cmp --silent -- "$OUTPUT_FILE" "$EXPECTED_FILE"; then
+  RunSolution <"$InputFile" | cat > "$OutputFile"
+
+  if test -f "$ExpectedOutputFile"; then
+    if cmp --silent -- "$OutputFile" "$ExpectedOutputFile"; then
       echo "Case $CaseId: Correct! :D"
     else
       echo "Case $CaseId: Wrong :("
@@ -154,8 +172,8 @@ RunTestCase() {
 }
 
 if [ "$Debug" = "true" ]; then
-  INPUT_FILE=workspace/$Problem/cases/$CaseId.in
-  time go run "$SOLUTION_FILE" <"$INPUT_FILE"
+  InputFile=workspace/$Problem/cases/$CaseId.in
+  time RunSolution < "$InputFile"
 elif [ "$RunAllTests" = "false" ]; then
   echo "Testing problem $Problem against test case $CaseId."
   RunTestCase
